/* v1.5C transport data adapter: only label information supported by its provider. */
(function(root,factory){const core=factory();if(typeof module==='object'&&module.exports)module.exports=core;if(root)root.TransportCore=core;})(typeof window!=='undefined'?window:null,function(){
 'use strict';
 const IDS=Object.freeze({bakerloo:'bakerloo',central:'central',circle:'circle',district:'district',hammersmithcity:'hammersmith-city',jubilee:'jubilee',metropolitan:'metropolitan',northern:'northern',piccadilly:'piccadilly',victoria:'victoria',waterloocity:'waterloo-city',elizabeth:'elizabeth',dlr:'dlr',tram:'tram',londonoverground:'',mildmay:'mildmay',windrush:'windrush',weaver:'weaver',lioness:'lioness',liberty:'liberty',suffragette:'suffragette'});
 function normalize(value){return String(value||'').toLowerCase().replace(/&/g,'and').replace(/\b(line|railway|underground|tube|service)\b/g,'').replace(/[^a-z0-9]/g,'').replace(/and/g,'');}
 function lineId(name){const key=normalize(name);if(IDS[key])return IDS[key];const bySuffix=key.endsWith('line')?key.slice(0,-4):key;return IDS[bySuffix]||null;}
 function steps(candidate){const result=[];for(const leg of candidate?.route?.legs||[])for(const step of leg.steps||[]){const t=step.transit||step.transit_details;if(t){result.push({line:String(t.line?.short_name||t.line?.name||t.line?.vehicle?.name||'Transit'),agency:String(t.line?.agencies?.[0]?.name||''),from:String(t.departure_stop?.name||''),to:String(t.arrival_stop?.name||''),departure:String(t.departure_time?.text||''),arrival:String(t.arrival_time?.text||''),headsign:String(t.headsign||''),stops:Number.isFinite(t.num_stops)?t.num_stops:null,mode:String(t.line?.vehicle?.type||t.line?.vehicle?.name||''),lineId:lineId(t.line?.name||t.line?.short_name)});}}return result;}
 function statusUrl(id){if(!Object.values(IDS).includes(id)||!id)return null;return `https://api.tfl.gov.uk/Line/${encodeURIComponent(id)}/Status`;}
 function statuses(data,id){if(!Array.isArray(data))throw Error('TfL returned an unexpected response');return data.filter(line=>line&&String(line.id||'')===id).flatMap(line=>(line.lineStatuses||[]).map(s=>({line:line.name||id,label:String(s.statusSeverityDescription||'Status unknown'),detail:String(s.reason||''),severity:Number(s.statusSeverity)})));}
 function isLondon(cityId){return cityId==='london';}
 function isTfL(t){return /transport for london|london underground|london overground|docklands light railway|elizabeth line/i.test(t.agency)||!!t.lineId;}
 const LINKS=Object.freeze({pay:'https://tfl.gov.uk/fares/ways-to-pay/pay-as-you-go',fare:'https://tfl.gov.uk/fares/find-fares/single-fare-finder',status:'https://tfl.gov.uk/status-updates/',access:'https://tfl.gov.uk/transport-accessibility/wheelchair-access-and-avoiding-stairs',accessiblePlanner:'https://tfl.gov.uk/transport-accessibility/plan-an-accessible-journey',timetable:'https://tfl.gov.uk/modes/tube/',journey:'https://tfl.gov.uk/plan-a-journey/'});
 return {IDS,LINKS,normalize,lineId,steps,statusUrl,statuses,isLondon,isTfL};
});
