/* v1.5F — opt-in travel planner. Drafts on THIS device, cloud only by explicit Sync. */
(function(){'use strict';
const C=window.EverythingTravelCore;if(!C||!document.getElementById('app'))return;
const root=document.getElementById('app'),$=id=>document.getElementById(id);
const LABELS={london:'London',rome:'Rome',istanbul:'İstanbul',izmir:'İzmir'};
const state={scope:null,trips:[],rows:new Map(),selected:null,tab:'timeline',status:'Travel plans are saved on this device unless you explicitly sync them.',open:false};
function node(tag,label,cls){const n=document.createElement(tag);if(label!==undefined)n.textContent=label;if(cls)n.className=cls;return n;}
function uid(){return 't'+Date.now().toString(36)+Math.random().toString(36).slice(2,11);}
function account(){return window.EverythingTripCloud;}
function scope(){return account()?.identity?.()||'guest';}
function key(){return 'everything.travel.v1:'+state.scope;}
function loadScope(){const id=scope();if(state.scope===id)return;state.scope=id;let items=[];try{const value=JSON.parse(localStorage.getItem(key())||'[]');if(Array.isArray(value))items=value.slice(0,30).map(t=>C.makeTrip(t));}catch{}state.trips=items;state.rows=new Map();state.selected=items[0]?.id||null;}
function saveLocal(){try{localStorage.setItem(key(),JSON.stringify(state.trips));return true;}catch{setStatus('Cannot save to this browser. Free storage or export a backup immediately.',true);return false;}}
function setStatus(msg,bad=false){state.status=msg;const el=$('v15f-travel-status');if(el){el.textContent=msg;el.classList.toggle('error',bad);}}
function current(){return state.trips.find(t=>t.id===state.selected)||null;}
function replace(t){const index=state.trips.findIndex(x=>x.id===t.id);if(index===-1){if(state.trips.length>=30)throw Error('Maximum 30 trips per device. Export or remove an old trip first.');state.trips.push(C.makeTrip(t));}else state.trips[index]=C.makeTrip(t);saveLocal();}
const toggle=node('button','🧳 Trips','v15f-trips-open');toggle.type='button';toggle.id='v15f-trips-open';toggle.setAttribute('aria-controls','v15f-travel-panel');toggle.setAttribute('aria-expanded','false');root.append(toggle);
const modal=node('section',undefined,'v15f-travel-panel hidden');modal.id='v15f-travel-panel';modal.setAttribute('aria-label','Travel Planner');modal.innerHTML=`<header class="v15f-travel-header"><div><small>OUR CITIES · v1.5F</small><h2>Travel Planner</h2></div><button type="button" id="v15f-travel-close" aria-label="Close Travel Planner">×</button></header><div id="v15f-travel-status" role="status" aria-live="polite"></div><div class="v15f-trip-chooser"><select id="v15f-trip-select" aria-label="Choose trip"></select><button id="v15f-trip-new" type="button">+ New</button><button id="v15f-trip-delete" type="button">Remove</button></div><nav id="v15f-travel-tabs" aria-label="Travel planner categories"></nav><div id="v15f-travel-body"></div><footer class="v15f-travel-footer"><button type="button" id="v15f-trip-sync">☁ Sync selected trip</button><button type="button" id="v15f-trip-refresh">↻ Load cloud</button><button type="button" id="v15f-trip-cloud-delete">✕ Delete cloud trip</button><button type="button" id="v15f-trip-export">↓ Export</button><button type="button" id="v15f-trip-import">↑ Import</button><input id="v15f-trip-file" type="file" accept="application/json,.json" hidden /></footer>`;root.append(modal);
const TABS=[['timeline','Timeline'],['packing','Packing'],['expenses','Expenses'],['documents','Expiry dates'],['details','Trip details']];
function open(){loadScope();state.open=true;modal.classList.remove('hidden');toggle.setAttribute('aria-expanded','true');$('settings-modal')?.classList.add('hidden');render();}
function close(){state.open=false;modal.classList.add('hidden');toggle.setAttribute('aria-expanded','false');}
toggle.onclick=()=>state.open?close():open();$('v15f-travel-close').onclick=close;
$('settings-modal')?.querySelector('#accounts-btn')?.insertAdjacentElement('afterend',(()=>{const btn=node('button','🧳 Travel Planner','secondary-btn');btn.type='button';btn.onclick=open;return btn;})());
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.open)close();});
function input(label,id,type='text',value='',max=undefined){const wrap=node('label',undefined,'v15f-field');wrap.append(node('span',label));const inp=node('input');inp.id=id;inp.type=type;inp.className='form-control';if(type==='number'){inp.min='0';inp.step='0.01';}if(max)inp.maxLength=max;inp.value=value===null?'':String(value);wrap.append(inp);return inp.parentElement;}
function select(label,id,options,value){const wrap=node('label',undefined,'v15f-field');wrap.append(node('span',label));const sel=node('select');sel.id=id;sel.className='form-control';for(const [val,name] of options){const op=node('option',name);op.value=val;sel.append(op);}sel.value=value;wrap.append(sel);return wrap;}
function action(label,fn,cls='v15f-action'){const b=node('button',label,cls);b.type='button';b.onclick=fn;return b;}
function legend(parent,msg){parent.append(node('p',msg,'v15f-explain'));}
function render(){if(!state.open)return;loadScope();const select=$('v15f-trip-select');select.replaceChildren();for(const trip of state.trips){const opt=node('option',trip.name+' · '+LABELS[trip.city]);opt.value=trip.id;select.append(opt);}if(!current()&&state.trips.length)state.selected=state.trips[0].id;select.value=state.selected||'';
 $('v15f-trip-delete').disabled=!current();$('v15f-trip-cloud-delete').disabled=!current()||!state.rows.get(current()?.id)||state.rows.get(current()?.id)?.author_id!==account()?.identity?.();$('v15f-trip-sync').disabled=!current()||!account()?.ready?.();$('v15f-trip-refresh').disabled=!account()?.ready?.();setStatus(state.status);
 const tabs=$('v15f-travel-tabs');tabs.replaceChildren();for(const [id,title] of TABS){const b=action(title,()=>{state.tab=id;render();},'v15f-tab'+(state.tab===id?' active':''));b.setAttribute('aria-pressed',String(state.tab===id));tabs.append(b);}
 const body=$('v15f-travel-body');body.replaceChildren();const trip=current();if(!trip){legend(body,'Create a trip to start. Data stays on this device until you explicitly sync.');return;}
 const status=node('div',undefined,'v15f-sync-badge'),remote=state.rows.get(trip.id);status.textContent=remote?'☁ Synced version found · changes on this device require Sync':'◉ Device copy · not yet synced';body.append(status);
 try{({timeline:timeline,packing:packing,expenses:expenses,documents:documents,details:details}[state.tab]||timeline)(body,trip);}catch(error){legend(body,'Unable to display this trip: '+error.message);}
}
function changeTrip(mutator){const trip=current();if(!trip)return;mutator(trip);replace(trip);setStatus('Saved to this device. Use Sync to share or update cloud.');render();}
$('v15f-trip-select').onchange=e=>{state.selected=e.target.value;render();};
$('v15f-trip-new').onclick=()=>{loadScope();if(state.trips.length>=30){setStatus('Maximum 30 trips. Export or remove an old trip first.',true);return;}
 const city=typeof currentCityId!=='undefined'&&C.CITIES.includes(currentCityId)?currentCityId:'london',trip=C.makeTrip({id:uid(),name:'New trip',city});replace(trip);state.selected=trip.id;state.tab='details';render();};
$('v15f-trip-delete').onclick=async()=>{const trip=current();if(!trip||!confirm('Remove '+trip.name+' from THIS device? A cloud version, if any, remains until separately removed. Export a backup first if needed.'))return;state.trips=state.trips.filter(t=>t.id!==trip.id);state.selected=state.trips[0]?.id||null;state.rows.delete(trip.id);saveLocal();setStatus('Removed from this device. Existing cloud records remain.');render();};
function details(parent,trip){
 const section=node('section',undefined,'v15f-card');section.append(node('h3','Plan your trip'));
 for(const item of [input('Trip name','v15f-name','text',trip.name,100),select('City','v15f-city',Object.entries(LABELS),trip.city),input('Start date','v15f-start','date',trip.start),input('End date','v15f-end','date',trip.end),select('Visibility','v15f-sharing',[['private','Private · only my account'],['together','Together · both can read and edit']],trip.sharing)])section.append(item);
 const memo=node('label',undefined,'v15f-field');memo.append(node('span','Notes (no passport numbers or confidential records)'));const ta=node('textarea');ta.className='form-control';ta.id='v15f-memo';ta.maxLength=1500;ta.rows=3;ta.value=trip.memo||'';memo.append(ta);section.append(memo);
 legend(section,'Private trips synchronize only to your own account. Together trips become visible to your partner ONLY after Sync succeeds. You cannot change sharing of an existing cloud record; export and create a new trip instead.');
 section.append(action('Save trip details',()=>{const name=$('v15f-name').value.trim(),start=$('v15f-start').value,end=$('v15f-end').value;if(!name)return setStatus('Trip name required.',true);if(start&&end&&start>end)return setStatus('End date must not precede the start date.',true);const previous=state.rows.get(trip.id);if(previous&&(previous.collection==='together')!==($('v15f-sharing').value==='together'))return setStatus('Sharing of an existing cloud record cannot be changed. Export and create a new trip instead.',true);changeTrip(t=>{t.name=name;t.city=$('v15f-city').value;t.start=start;t.end=end;t.sharing=$('v15f-sharing').value;t.memo=$('v15f-memo').value;});}));parent.append(section);
}
function timeline(parent,trip){
 const section=node('section',undefined,'v15f-card');section.append(node('h3',trip.name+' · timeline'));legend(section,'Flights, reservations, journeys and meetings. Times are entered in local time for the chosen city; verify time-zone differences on tickets. Dragging is not required: use ↑ / ↓ to reorder stops.');
 const sorted=trip.itinerary;
 sorted.forEach((stop,index)=>{const row=node('div',undefined,'v15f-list-item');const date=[stop.day,stop.time].filter(Boolean).join(' · ');row.append(node('strong',`${stop.kind.toUpperCase()} · ${stop.title||'Untitled'}`));row.append(node('small',[date,LABELS[stop.city],stop.place].filter(Boolean).join(' · ')));if(stop.details)row.append(node('p',stop.details));const actions=node('div',undefined,'v15f-item-actions');actions.append(action('↑',()=>changeTrip(t=>{if(index>0)[t.itinerary[index-1],t.itinerary[index]]=[t.itinerary[index],t.itinerary[index-1]];})),action('↓',()=>changeTrip(t=>{if(index<t.itinerary.length-1)[t.itinerary[index+1],t.itinerary[index]]=[t.itinerary[index],t.itinerary[index+1]];})),action('Remove',()=>changeTrip(t=>t.itinerary.splice(index,1))));row.append(actions);section.append(row);});
 if(sorted.length>=200){legend(section,'Maximum 200 itinerary entries reached.');parent.append(section);return;}
 const add=node('div',undefined,'v15f-entry-form');add.append(node('h4','Add an itinerary stop'));
 add.append(select('Type','v15f-stop-kind',[['flight','Flight'],['reservation','Reservation'],['journey','Journey'],['meeting','Meeting'],['other','Other']],'journey'),input('Title','v15f-stop-title','text','',130),input('Date','v15f-stop-day','date',trip.start),input('Local time','v15f-stop-time','time',''),select('City for this stop','v15f-stop-city',Object.entries(LABELS),trip.city),input('Place / terminal / address','v15f-stop-place','text','',150),input('Reference / details (avoid sensitive document data)','v15f-stop-details','text','',500));
 add.append(action('Add stop',()=>{const title=$('v15f-stop-title').value.trim();if(!title)return setStatus('Enter a stop title first.',true);changeTrip(t=>t.itinerary.push({id:uid(),title,kind:$('v15f-stop-kind').value,day:$('v15f-stop-day').value,time:$('v15f-stop-time').value,city:$('v15f-stop-city').value,place:$('v15f-stop-place').value,details:$('v15f-stop-details').value}));}));section.append(add);parent.append(section);
}
function packing(parent,trip){const box=node('section',undefined,'v15f-card');const done=trip.packing.filter(x=>x.done).length;box.append(node('h3',`Packing · ${done}/${trip.packing.length}`));for(const entry of trip.packing){const row=node('div',undefined,'v15f-check-item');const label=node('label');const ck=node('input');ck.type='checkbox';ck.checked=entry.done;ck.onchange=e=>changeTrip(t=>{const x=t.packing.find(i=>i.id===entry.id);if(x)x.done=e.target.checked;});label.append(ck,node('span',entry.item));row.append(label,action('×',()=>changeTrip(t=>t.packing=t.packing.filter(i=>i.id!==entry.id))));box.append(row);}const form=node('div',undefined,'v15f-add-row');form.append(input('Add a packing item','v15f-pack-new','text','',120),action('Add',()=>{const value=$('v15f-pack-new').value.trim();if(value)changeTrip(t=>{if(t.packing.length<250)t.packing.push({id:uid(),item:value,done:false});});}));box.append(form);parent.append(box);}
function expenses(parent,trip){const box=node('section',undefined,'v15f-card');box.append(node('h3','Expenses · by currency'));legend(box,'Totals are separated by currency; no invented live exchange rates or double counting.');const totals=C.totals(trip.expenses);for(const [currency,value] of Object.entries(totals))box.append(node('strong',currency+' '+value.toFixed(2),'v15f-total'));for(const item of trip.expenses){const row=node('div',undefined,'v15f-list-item');row.append(node('span',item.item+' · '+item.currency+' '+item.amount.toFixed(2)),action('Remove',()=>changeTrip(t=>t.expenses=t.expenses.filter(x=>x.id!==item.id))));box.append(row);}const form=node('div',undefined,'v15f-entry-form');form.append(input('Description','v15f-exp-name','text','',120),input('Amount','v15f-exp-amount','number','0'),select('Currency','v15f-exp-currency',C.CURRENCIES.map(x=>[x,x]),trip.city==='rome'?'EUR':trip.city==='london'?'GBP':'TRY'),action('Add expense',()=>{const name=$('v15f-exp-name').value.trim(),val=Number($('v15f-exp-amount').value);if(!name||!Number.isFinite(val)||val<0||val>100000000)return setStatus('Enter a name and valid non-negative amount.',true);changeTrip(t=>{if(t.expenses.length<250)t.expenses.push({id:uid(),item:name,amount:val,currency:$('v15f-exp-currency').value});});}));box.append(form);parent.append(box);}
function documents(parent,trip){const box=node('section',undefined,'v15f-card');box.append(node('h3','Document expiry reminders'));legend(box,'Metadata ONLY: label and expiration date. No scans, passport or visa numbers, credentials, photographs or ticket files. These entries are stored in browser storage and included in trip exports/cloud sync when enabled.');const today=new Date().toISOString().slice(0,10);for(const item of trip.documents){const days=C.daysUntil(item.expiry,today),row=node('div',undefined,'v15f-list-item');row.append(node('strong',item.label||'Document'));row.append(node('span',`${item.expiry||'No expiry entered'} · ${days===null?'date unavailable':days<0?'EXPIRED '+Math.abs(days)+' days ago':days<=30?'Expires in '+days+' days':'Expires in '+days+' days'}`,days!==null&&days<=30?'v15f-warning':''));row.append(action('Remove',()=>changeTrip(t=>t.documents=t.documents.filter(x=>x.id!==item.id))));box.append(row);}const form=node('div',undefined,'v15f-entry-form');form.append(input('Document nickname (e.g. passport)','v15f-doc-name','text','',120),input('Expiry date','v15f-doc-expiry','date',''),action('Add reminder',()=>{const label=$('v15f-doc-name').value.trim(),expiry=$('v15f-doc-expiry').value;if(!label||!C.date(expiry))return setStatus('Enter a nickname and valid expiry date.',true);changeTrip(t=>{if(t.documents.length<30)t.documents.push({id:uid(),label,expiry});});}));box.append(form);parent.append(box);}
async function sync(){const trip=current(),cloud=account();if(!trip||!cloud?.ready?.())return setStatus('Sign in and finish Supabase pairing to sync.',true);const prev=state.rows.get(trip.id);$('v15f-trip-sync').disabled=true;setStatus('Saving using your existing Supabase account and RLS permissions…');try{const row=await cloud.save(trip,prev);state.rows.set(trip.id,row);setStatus('Cloud sync succeeded. Together is visible to your partner if selected; your private trips remain author-only.');}catch(e){setStatus('Sync failed: '+e.message+' Your on-device draft remains safe.',true);}finally{render();}}
$('v15f-trip-sync').onclick=sync;
$('v15f-trip-cloud-delete').onclick=async()=>{const trip=current(),previous=trip&&state.rows.get(trip.id);if(!previous)return setStatus('No cloud record for this trip.',true);
 if(previous.author_id!==account()?.identity?.())return setStatus('Only the trip creator can remove it from the cloud.',true);
 if(!confirm(`Remove "${trip.name}" from the cloud for both people? The original record remains in Supabase history. Your local device copy is preserved.`))return;
 try{await account().remove(previous);state.rows.delete(trip.id);setStatus('Cloud trip removed; this device copy remains. Delete it separately if desired.');render();}catch(e){setStatus('Cloud delete failed: '+e.message,true);}
};
$('v15f-trip-refresh').onclick=async()=>{const cloud=account();if(!cloud?.ready?.())return setStatus('Sign in and pair accounts first.',true);setStatus('Loading cloud travel plans…');try{const rows=await cloud.list();let added=0,updated=0;for(const row of rows){const trip=C.makeTrip(row.payload.trip);const local=state.trips.find(x=>x.id===trip.id);if(local&&JSON.stringify(local)!==JSON.stringify(trip)){// protect unsynced device edits; never overwrite without consent.
 if(!confirm(`Cloud version for "${trip.name}" differs from this device. Replace this device copy with cloud version? Cancel preserves your device draft.`))continue;updated++;
 }else if(!local)added++;
 state.rows.set(trip.id,row);replace(trip);
 }setStatus(`Cloud loaded: ${added} added, ${updated} updated. Other local drafts preserved.`);render();}catch(e){setStatus('Cloud refresh failed: '+e.message,true);}};
function download(value,filename){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('v15f-trip-export').onclick=()=>{loadScope();download({format:'everything-trip-v1',exportedAt:new Date().toISOString(),trips:state.trips},'our-cities-travel-backup.json');setStatus('Export downloaded. The file is NOT encrypted; store it privately.');};
$('v15f-trip-import').onclick=()=>$('v15f-trip-file').click();
$('v15f-trip-file').onchange=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>2*1024*1024)return setStatus('Import must be smaller than 2 MB.',true);try{const incoming=C.validImport(JSON.parse(await file.text()));if(!confirm(`Import ${incoming.length} trips? Matching trip IDs will replace local copies. Export a backup first. Cloud records will NOT be changed until you explicitly Sync.`))return;for(const trip of incoming)replace(trip);state.selected=incoming[0]?.id||state.selected;setStatus('Trips imported to this device. Cloud not changed.');render();}catch(err){setStatus('Import failed: '+err.message,true);}};
window.EverythingTravel={open,close};
})();
